/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sinhvien;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.runtime.Debug.id;

/**
 *
 * @author ADMIN
 */
public class UpdateInfoStudent extends javax.swing.JFrame {
    private Object txtPrice;
    private Object txtTitle;
    private Object cmbCondition;
    private Object lblStatus;
    private int ID_Student;

    /**
     * Creates new form Class
     */
    public UpdateInfoStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CbBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID_Student");

        CbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Name_Student");

        jLabel3.setText("Update Info Student");

        jLabel4.setText("Age");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CbBox, 0, 166, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(337, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(46, 46, 46)
                .addComponent(jButton2)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbBoxActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
    PreparedStatement ps = null;
ResultSet rs = null;
try {
 conn = DriverManager.getConnection("jdbc:sqlserver://localhost;DatabaseName=Java2", "sa", "1234"); 
            int ID_Student = Integer.parseInt((String) cmbCondition.getSelectedItem());
 String sql = "Select * from Student where ID_Student = ?";
 ps = conn.prepareStatement(sql); 
 ps.setInt(1, ID_Student);
 rs = ps.executeQuery();
 if (rs.next()) {
  //Hiển thị dữ liệu vào các textfield
  txtTitle.setText(rs.getString("title"));
  txtPrice.setText(rs.getString("price"));
 } 
} catch (Exception e) {
 e.printStackTrace();
} finally {
 try {
  if (conn != null) {
   conn.close();
  }
  if (rs != null) {
   rs.close();
  }
  if (ps != null) {
   ps.close();
  }
 } catch (Exception ex2) {
   ex2.printStackTrace();
 }
}
        Connection conn = null;
        Statement st = null;
        ResultSet rs = null;
try {
 conn = DriverManager.getConnection("jdbc:sqlserver://localhost;DatabaseName=Java2", "sa", "1234");
 st = conn.createStatement();
 rs = st.executeQuery("select ID form Student ");
 Vector data = new Vector();
 while (rs.next()) {
   data.add(rs.getString("id"));
 }
            DefaultComboBoxModel cmbModel = new DefaultComboBoxModel(data);
 cmbCondition.setModel(cmbModel);
} catch (Exception e) {
 e.printStackTrace();
} finally {
 try {
   if (conn != null) {
     conn.close();
   }
  if (st != null) {
    st.close();
 }
  if (rs != null) {
    rs.close();
  }
 } catch (Exception ex) {
  ex.printStackTrace();
 }
}
    }//GEN-LAST:event_CbBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int ret = JOptionPane.showConfirmDialog(this, "Do you want to update?", "Confirm", JOptionPane.YES_NO_OPTION);
if (ret != JOptionPane.YES_OPTION) {
 return;
}
String update = "update Student set Name_Student = ?, Age = ? where ID_Student = ?";
System.out.println(update);
Connection conn = null;
PreparedStatement ps = null;
ResultSet rs = null;
try {
 conn = DriverManager.getConnection("jdbc:sqlserver://localhost;DatabaseName=Java2", "sa", "1234");
 ps = conn.prepareStatement(update);
 ps.setString(1, txtTitle.getText());
 ps.setFloat(2, Float.parseFloat(txtPrice.getText()));
 ps.setInt(3, ID_Student); //id được chọn từ combobox
 ret = ps.executeUpdate();
 if (ret != -1) {
   lblStatus.setText("Info Student has been updated");
 }
} catch (Exception e) {
 e.printStackTrace();
} finally {
 try {
  if (conn != null) {
   conn.close();
  }
  if(rs != null) {
   rs.close();
  }
  if (ps != null) {
   ps.close();
  }
 } catch (Exception ex2) {
  ex2.printStackTrace();
 }
}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateInfoStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateInfoStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateInfoStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateInfoStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateInfoStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CbBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
